apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: webapp
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: webapp
      containers:
      - name: app
        image: ghcr.io/bdarge/simple-vault-client:latest
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: "https://192.168.50.76:8200"
        - name: JWT_PATH
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - name: SERVICE_PORT
          value: "8082"
        - name: AUTH_PATH
          value: "auth/k8s-remote/login"
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-api-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      name: http
      targetPort: 8082
  selector:
    app: webapp
